version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: fbase-postgres
    environment:
      POSTGRES_DB: project1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:4
    container_name: fbase-adminer
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8081:8080"
    restart: unless-stopped

networks:
  default:
    name: fbase-net
